
#DIR=Platform/md5 Platform/encoding WordSegmentor AdLog AdUtil StringUtil RTermQuery MatchCommon QueryAnalyzer ADRCommon AdRetriever Relevance RelevanceTrainer
#DIR=Platform/md5 Platform/encoding WordSegmentor GraphCommon Test
DIR=GraphCommon GraphBase Test

export AD_CODE_ROOT = $(shell pwd)

include Makefile.dir
